services:
  course_api:
    build:
      context: ./course_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: course_api
    restart: unless-stopped
    ports:
      - "80:8081"
  
  student_api:
    build:
      context: ./student_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: student_api
    restart: unless-stopped
    ports:
      - "82:8081"



  teacher_api:
    build:
      context: ./teacher_api
      dockerfile: Dockerfile
    #image: nodejs
    container_name: teacher_api
    restart: unless-stopped
    ports:
      - "81:8081"